services:
  web:
    build: .
    container_name: autonovin_django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=${DEBUG}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL = ${CELERY_BROKER}
      - CELERY_RESULT_BACKEND = ${CELERY_BACKEND}

  db:
    image: postgres:13
    container_name: autonovin_postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: autonovin_redis
    ports:
      - "6379:6379"

  chroma:
    image: chromadb/chroma
    container_name: autonovin_chroma
    ports:
      - "8002:8000"

  celery:
    build: .
    container_name: autonovin_celery_worker
    command: celery --app=autonovin worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    environment:
      - DEBUG=${DEBUG}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}

volumes:
  postgres_data:
